<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataweb" nsURI="http://www.unex.es/dmss/dataweb" nsPrefix="dataweb">
  <eAnnotations source="gmf"/>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="operationReflection" value="true"/>
    <details key="tableProviders" value="true"/>
    <details key="complianceLevel" value="6.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Aplicacion">
    <eAnnotations source="gmf.diagram"/>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R01_una_sola_pagina_home R04_al_menos_una_red_social_y_rss R06b_al_menos_una_encuesta_y_cuestionario"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R01_una_sola_pagina_home" value="self.paginas->select(p | p.oclIsTypeOf(PaginaHome))->size() = 1"/>
      <details key="R04_al_menos_una_red_social_y_rss" value="self.redesSociales->size() >= 1 and self.fuentesRSS->size() >= 1"/>
      <details key="R06b_al_menos_una_encuesta_y_cuestionario" value="self.encuestas->size() >= 1 and self.cuestionarios->size() >= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" lowerBound="1"
        upperBound="-1" eType="#//Entidad" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginas" lowerBound="1"
        upperBound="-1" eType="#//Pagina" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="1" upperBound="-1"
        eType="#//Rol" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cuestionarios" upperBound="-1"
        eType="#//Cuestionario" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encuestas" upperBound="-1"
        eType="#//Encuesta" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redesSociales" lowerBound="1"
        upperBound="-1" eType="#//RedSocial" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuentesRSS" lowerBound="1"
        upperBound="-1" eType="#//FuenteRSS" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paginasMediasAccesibles"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="200,200,255"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R02_crud_incompatible R03_indice_requiere_detalle R05_no_autorreferencia R06_no_referencia_circular R08_solo_una_pagina_indice R09_atributos_pertenecen_entidad"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R02_crud_incompatible" value="self.hasCRUD implies (not self.hasIndex and not self.hasExtendedIndex and not self.hasDetails and not self.hasCreate and not self.hasUpdate and not self.hasDelete)"/>
      <details key="R03_indice_requiere_detalle" value="(self.hasIndex or self.hasExtendedIndex) implies self.hasDetails"/>
      <details key="R05_no_autorreferencia" value="self.referencias->forAll(r | r.target &lt;> self)"/>
      <details key="R06_no_referencia_circular" value="self.referencias->forAll(r | r.target.referencias->forAll(r2 | r2.target &lt;> self))"/>
      <details key="R08_solo_una_pagina_indice" value="Pagina.allInstances()->select(p | p.oclIsKindOf(PaginaIndice) and p.oclAsType(PaginaCRUD).entidad = self)->size() &lt;= 1"/>
      <details key="R09_atributos_pertenecen_entidad" value="Pagina.allInstances()->select(p | p.oclIsKindOf(PaginaIndice))->forAll(pi | pi.oclAsType(PaginaIndice).atributosMostrados->forAll(a | a.oclContainer() = pi.oclAsType(PaginaCRUD).entidad))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasCRUD" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasExtendedIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasDetails" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasCreate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasUpdate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasDelete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencias" upperBound="-1"
        eType="#//Referencia" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,255,200"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimaryKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="#//TipoAtributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoAtributo">
    <eLiterals name="STRING"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="DECIMAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referencia">
    <eAnnotations source="gmf.link">
      <details key="label" value="nombre"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="color" value="100,100,100"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidad" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Entidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pagina" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="150,255,150"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enlaces" upperBound="-1"
        eType="#//Pagina">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,150,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redesSociales" upperBound="-1"
        eType="#//RedSocial">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="255,100,0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fuentesRSS" upperBound="-1"
        eType="#//FuenteRSS">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,100,255"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaHome" eSuperTypes="#//Pagina">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="100,255,100"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaContenido" eSuperTypes="#//Pagina">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="150,255,200"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenido" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaCRUD" abstract="true" eSuperTypes="#//Pagina">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="200,150,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidad" lowerBound="1"
        eType="#//Entidad">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="150,0,150"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaIndice" abstract="true" eSuperTypes="#//PaginaCRUD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,200,150"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributosMostrados" lowerBound="1"
        upperBound="-1" eType="#//Atributo">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="200,100,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaDetalle" eSuperTypes="#//PaginaCRUD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,150,150"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaCreacion" eSuperTypes="#//PaginaCRUD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="150,255,255"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaActualizacion" eSuperTypes="#//PaginaCRUD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,255,150"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaBorrado" eSuperTypes="#//PaginaCRUD">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,100,100"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaIndiceDetalle" eSuperTypes="#//PaginaIndice">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="200,255,200"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Encuesta">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="100,200,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preguntas" lowerBound="1"
        upperBound="-1" eType="#//Pregunta" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoRepresentacion" lowerBound="1"
        eType="#//TipoRepresentacion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregVF" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregSelect" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoRepresentacion">
    <eLiterals name="TEXTO"/>
    <eLiterals name="BARRAS" value="1"/>
    <eLiterals name="CIRCULAR" value="2"/>
    <eLiterals name="LINEAS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoRedSocial">
    <eLiterals name="TWITTER"/>
    <eLiterals name="FACEBOOK" value="1"/>
    <eLiterals name="INSTAGRAM" value="2"/>
    <eLiterals name="LINKEDIN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cuestionario">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,200,100"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R07_cuestionarios_con_respuesta"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R07_cuestionarios_con_respuesta" value="self.preguntas->forAll(p | p.oclIsTypeOf(PreguntaOpcionMultiple) implies p.oclAsType(PreguntaOpcionMultiple).respuestaCorrecta &lt;> null)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preguntas" lowerBound="1"
        upperBound="-1" eType="#//Pregunta" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregVF" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregSelect" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pregunta" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="200,255,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texto" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreguntaOpcionMultiple" eSuperTypes="#//Pregunta">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,220,220"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opciones" lowerBound="2"
        upperBound="-1" eType="#//OpcionRespuesta" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respuestaCorrecta" eType="#//OpcionRespuesta">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="255,0,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpcionRespuesta">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="220,255,220"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="texto" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreguntaVerdaderoFalso" eSuperTypes="#//Pregunta">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="220,220,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="respuestaCorrecta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreguntaRespuestaCorta" eSuperTypes="#//Pregunta">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,255,220"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="respuestaCorta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedSocial">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,150,0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="#//TipoRedSocial"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigoEmbed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreCuenta" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rol">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="100,100,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paginasAccesibles" lowerBound="1"
        upperBound="-1" eType="#//Pagina">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,0,200"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroEntidadesAccesibles"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuenteRSS">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="0,255,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titulo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numItems" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mostrarDescripcion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaIndicePaginada" eSuperTypes="#//PaginaIndice">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="255,180,120"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaIndiceFiltros" eSuperTypes="#//PaginaIndice">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="180,255,120"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributosFiltro" upperBound="-1"
        eType="#//Atributo">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="100,200,0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaginaIndicePaginadaFiltrada" eSuperTypes="#//PaginaIndice">
    <eAnnotations source="gmf.node">
      <details key="label" value="nombre"/>
      <details key="color" value="120,180,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributosFiltro" upperBound="-1"
        eType="#//Atributo">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="color" value="0,100,200"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
