pluginName=Dataweb Plugin
providerName=Sample Plugin Provider, Inc

editorName=Dataweb Diagram Editing
context.description=Dataweb Diagram Editing
context.name=In Dataweb Diagram Editor
newWizardName=Dataweb Diagram
newWizardDesc=Creates Dataweb diagram.

initDiagramActionLabel=Initialize dataweb_diagram diagram file


navigatorContentName=*.dataweb_diagram diagram contents
domainNavigatorContentName=*.dataweb model contents
update.diagram.name=Update Dataweb diagram
update.diagram.description=Perform Dataweb diagram update


# Property Sheet
tab.appearance=Appearance
tab.diagram=Rulers & Grid
tab.domain=Core

# Preferences
prefpage.dmss.dataweb.diagram.general=Dataweb Diagram
prefpage.dmss.dataweb.diagram.appearance=Appearance
prefpage.dmss.dataweb.diagram.connections=Connections
prefpage.dmss.dataweb.diagram.printing=Printing
prefpage.dmss.dataweb.diagram.rulersAndGrid=Rulers And Grid


# Providers
metatype.name.Aplicacion_1000=Undefined
metatype.name.PaginaIndiceDetalle_2001=PaginaIndiceDetalle
metatype.name.PaginaIndicePaginada_2002=PaginaIndicePaginada
metatype.name.PaginaIndiceFiltros_2003=PaginaIndiceFiltros
metatype.name.PaginaIndicePaginadaFiltrada_2004=PaginaIndicePaginadaFiltrada
metatype.name.PaginaDetalle_2005=PaginaDetalle
metatype.name.PaginaCreacion_2006=PaginaCreacion
metatype.name.PaginaActualizacion_2007=PaginaActualizacion
metatype.name.PaginaBorrado_2008=PaginaBorrado
metatype.name.PaginaHome_2009=PaginaHome
metatype.name.PaginaContenido_2010=PaginaContenido
metatype.name.Entidad_2011=Entidad
metatype.name.Rol_2012=Rol
metatype.name.Cuestionario_2013=Cuestionario
metatype.name.Encuesta_2014=Encuesta
metatype.name.RedSocial_2015=RedSocial
metatype.name.FuenteRSS_2016=FuenteRSS
metatype.name.Atributo_3001=Atributo
metatype.name.PreguntaOpcionMultiple_3002=PreguntaOpcionMultiple
metatype.name.OpcionRespuesta_3003=OpcionRespuesta
metatype.name.PreguntaVerdaderoFalso_3004=PreguntaVerdaderoFalso
metatype.name.PreguntaRespuestaCorta_3005=PreguntaRespuestaCorta
metatype.name.PreguntaOpcionMultiple_3006=PreguntaOpcionMultiple
metatype.name.PreguntaVerdaderoFalso_3007=PreguntaVerdaderoFalso
metatype.name.PreguntaRespuestaCorta_3008=PreguntaRespuestaCorta
metatype.name.Referencia_4001=Referencia
metatype.name.PaginaEnlaces_4002=Undefined
metatype.name.PaginaRedesSociales_4003=Undefined
metatype.name.PaginaFuentesRSS_4004=Undefined
metatype.name.PaginaCRUDEntidad_4005=Undefined
metatype.name.PaginaIndiceAtributosMostrados_4006=Undefined
metatype.name.PreguntaOpcionMultipleRespuestaCorrecta_4007=Undefined
metatype.name.RolPaginasAccesibles_4008=Undefined
metatype.name.PaginaIndiceFiltrosAtributosFiltro_4009=Undefined
metatype.name.PaginaIndicePaginadaFiltradaAtributosFiltro_4010=Undefined

# Commands and menu actions
cmdcategory.name=Dataweb Editor Commands
cmdcategory.desc=Dataweb Editor Commands

